
export const CLOCK_MARKERS = [
  { type: 'main', number: '12' },
  { type: 'minor' },
  { type: 'minor' },
  { type: 'minor' },
  { type: 'minor' },
  { type: 'main', number: '1' },
  { type: 'minor' },
  { type: 'minor' },
  { type: 'minor' },
  { type: 'minor' },
  { type: 'main', number: '2' },
  { type: 'minor' },
  { type: 'minor' },
  { type: 'minor' },
  { type: 'minor' },
  { type: 'main', number: '3' },
  { type: 'minor' },
  { type: 'minor' },
  { type: 'minor' },
  { type: 'minor' },
  { type: 'main', number: '4' },
  { type: 'minor' },
  { type: 'minor' },
  { type: 'minor' },
  { type: 'minor' },
  { type: 'main', number: '5' },
  { type: 'minor' },
  { type: 'minor' },
  { type: 'minor' },
  { type: 'minor' },
  { type: 'main', number: '6' },
  { type: 'minor' },
  { type: 'minor' },
  { type: 'minor' },
  { type: 'minor' },
  { type: 'main', number: '7' },
  { type: 'minor' },
  { type: 'minor' },
  { type: 'minor' },
  { type: 'minor' },
  { type: 'main', number: '8' },
  { type: 'minor' },
  { type: 'minor' },
  { type: 'minor' },
  { type: 'minor' },
  { type: 'main', number: '9' },
  { type: 'minor' },
  { type: 'minor' },
  { type: 'minor' },
  { type: 'minor' },
  { type: 'main', number: '10' },
  { type: 'minor' },
  { type: 'minor' },
  { type: 'minor' },
  { type: 'minor' },
  { type: 'main', number: '11' },
  { type: 'minor' },
  { type: 'minor' },
  { type: 'minor' },
  { type: 'minor' },
]
