export const WINDOW_NAMES: {[key: string]: string} = {
  skills: 'Skills',
  experience: 'Experience',
  education: 'Education',
  licenses: 'Licenses & Certification',
  contacts: 'Contacts',
  2048: '2048',
}

export const TECHNOLOGIES: {name: string, key: string}[] = [
  { name: 'React.js', key: 'reactjs'},
  { name: 'Next.js', key: 'nextjs'},
  { name: 'JavaScript', key: 'javascript' },
  { name: 'TypeScript', key: 'typescript' },
  { name: 'REST APIs', key: 'rest_api' },
  { name: 'React Hooks', key: 'react_hooks' },
  { name: 'Functional Programming', key: 'functional_programming' },
  { name: 'CSS', key: 'css' },
  { name: 'HTML5', key: 'html5'},
  { name: 'Agile Development', key: 'agile_development'},
  { name: 'Git', key: 'git'},
  { name: 'Redux', key: 'redux'},
  { name: 'JSON', key: 'json'},
  { name: 'OOP', key: 'oop'},
  { name: 'jQuery', key: 'jquery'},
  { name: 'GraphQL', key: 'graphql'},
  { name: 'TDD', key: 'tdd'},
  { name: 'Django', key: 'django'},
  { name: 'Celery', key: 'celery'},
  { name: 'Vue.js', key: 'vuejs'},
  { name: 'RabbitMQ', key: 'rabbitmq'},
  { name: 'Python', key: 'python'},
  { name: 'Angular', key: 'angular'},
]