import PowerPlayLogo from '../../../assets/images/companies/powerplay.png';
import HandiscoverLogo from '../../../assets/images/companies/haccess.png';
import EpamLogo from '../../../assets/images/companies/epam.png';

export const COMPANIES = [
  {
    name: 'PowerPlay',
    logo: PowerPlayLogo,
    site: 'https://powerplay.com/',
    date: 'Jun 2024 - Present',
    startDate: '2024-06',
    endDate: 'Present',
    position: 'Frontend Developer',
    type: 'Full-time',
    location: 'Remote',
    skills: [
      'reactjs',
      'nextjs',
      'typescript',
      'javascript',
      'html5',
      'css',
      'git',
      'react_hooks',
      'functional_programming',
      'rest_api',
      'json',
      'graphql',
    ]
  },
  {
    startDate: '2022-05',
    endDate: '2024-06',
    logo: HandiscoverLogo,
    name: 'Handiscover',
    site: 'https://www.haccess.io/',
    position: 'Frontend Developer',
    type: 'Full-time',
    location: 'Remote',
    skills: [
      'reactjs',
      'javascript',
      'typescript',
      'css',
      'react_hooks',
      'rest_api',
      'functional_programming',
      'git',
      'redux',
      'html5',
      'json',
    ],
    list: [
      'Consistently met my short and long-term targets.',
      'Proactively participated in meetings and helped create new practices.',
      'Pitched ideas on how to improve performance and efficiency.',
      'Helped management to identify workflow issues and find solutions.',
      'Development of several related projects where the first project is an admin panel and the second project is a client-side application.',
      'Development of pages/modules based on Figma mockups.',
      'Development of adaptive pages/modules.',
      'Implementation of new features into old code, refactoring, debugging, and bug fixing.',
      'Use/customization of the MaterialUI library for future pages.'
    ],
  },
  {
    startDate: '2022-01',
    endDate: '2022-05',
    logo: EpamLogo,
    name: 'EPAM',
    site: 'https://www.epam.com/',
    position: 'Frontend Developer',
    type: 'Full-time',
    location: 'Remote',
    skills: [
      'reactjs',
      'javascript',
      'typescript',
      'css',
      'react_hooks',
      'rest_api',
      'functional_programming',
      'git',
      'redux',
      'html5',
      'json',
    ],
    list: [
      'Сode debugging/refactoring to improve readability and efficiency.',
      'Developing new features and redesigning existing features to improve user experience.',
      'Writing quality tests and actively participating in the code review process.',
      'Applied agile development principles to ensure effective teamwork and timely delivery of results.',
      'Used Git and Redux version control system to effectively manage the state of the application'
    ]
  },
  {
    startDate: '2021-04',
    endDate: '2021-12',
    name: 'Forex Tester Software',
    site: 'https://forextester.com/',
    position: 'Frontend Developer',
    type: 'Full-time',
    location: 'Hybrid',
    skills: [
      'rest_api',
      'javascript',
      'functional_programming',
      'css',
      'html5',
      'agile_development',
      'react_hooks',
      'git',
      'redux',
      'reactjs',
      'html',
      'json',
      'oop',
      'jquery',
      'typescript',
      'tdd',
    ],
    list: [
      'Implemented an online chat assistant for websites using an iframe.',
      'Development of pages/modules based on Figma mockups.',
      'Development of adaptive pages/modules.',
      'Сode reviews',
      'Implementation of new features into old code, refactoring, and debugging.',
    ]
  },
  {
    startDate: '2019-05',
    endDate: '2021-03',
    name: 'BeHealthy.AI',
    position: 'Frontend & Backend Developer',
    type: 'Full-time',
    location: 'On-Site',
    skills: [
      'rest_api',
      'django',
      'javascript',
      'functional_programming',
      'css',
      'html5',
      'celery',
      'agile_development',
      'react_hooks',
      'git',
      'redux',
      'vuejs',
      'json',
      'oop',
      'jquery',
      'rabbitmq',
      'python',
      'typescript',
      'angular',
      'tdd',
    ],
    list: [
      'Developed a questionnaire page with dynamically pulling up new next questions from the BE side.',
      'Development of pages/modules based on Figma mockups.',
      'Development of adaptive pages/modules.',
      'Implementation of new features into old code, refactoring, and debugging.',
      'Development of endpoints on Django, development of components on VueJS.',
      'Сode reviews',
      'Writing tests'
    ]
  }


]